version: 0.2
phases:
  install:
    runtime-version:
      nodejs: latest
    command:
      - echo install dependencies
      - npm install
  pre-build:
    command:
      - No anything in pre-build
  build:
    command:
      - npm run build
  post-build:
    command:
      - Push artifact to S3
      - aws s3 cp --recursive ./dist s3://cicd-web-application-demo/nodejs_artifact/

artifacts:
  files:
    - dist/**
  discard-paths: yes      