version: 0.2
phases:
  pre_build:
    commands:
    - echo Nothing in the pre-build
  build:
    commands:
      - echo install source dependencies 
      - npm install
  post_build:
    commands:
      - aws s3 cp --recursive ./dist s3://cicd-web-application-demo/nodejs_artifact/
artifacts:
  files: 
    - dist/**
  discard-paths: yes