version: 0.2
phases:
  install:
    runtime-version:
      nodejs: latest
    commands:
      - npm install
  pre_build:
    commands:
    - echo Nothing in the pre-build
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive . s3://cicd-web-application-demo/nodejs_artifact/
artifacts:
  files: 
    - '**/*'
    - '!node_modules/**/*'